// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID      int32  `gorm:"column:id;type:int;primaryKey" json:"Id"`
	OrderID int32  `gorm:"column:order_id;type:int" json:"OrderId"`
	UserID  int32  `gorm:"column:user_id;type:int" json:"UserId"`
	Product string `gorm:"column:product;type:varchar(255)" json:"Product"`
	Amount  int32  `gorm:"column:amount;type:int" json:"Amount"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
