// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"Id"`
	RealName  string `gorm:"column:real_name;type:varchar(255)" json:"RealName"`
	IDCard    string `gorm:"column:id_card;type:varchar(255)" json:"IdCard"`
	HfAccount string `gorm:"column:hf_account;type:varchar(255)" json:"HfAccount"`
	HfAcctID  string `gorm:"column:hf_acct_id;type:varchar(255)" json:"HfAcctId"`
	Mobile    string `gorm:"column:mobile;type:varchar(255)" json:"Mobile"`
	Email     string `gorm:"column:email;type:varchar(255)" json:"Email"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
