version: '3'
services:
  neo4j:
    image: neo4j:4.4.27
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./tmp:/tmp
      - ./data:/data
      - ./logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      - NEO4J_dbms_security_http_access_control_allow_origin=*
      - NEO4J_dbms_security_http_access_control_allow_methods=GET,POST,PUT,DELETE,OPTIONS
      - NEO4J_dbms_security_http_access_control_allow_headers=Content-Type,Authorization