version: '3'
services:
  redis:
    image: redis:7.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
#      - /docker-compose/redis/data:/data
      - ~/redis/redis.conf:/usr/local/etc/redis/redis.conf