version: '3'
services:
  prometheus:
    container_name: kibana
    image: kibana:7.17.22
    ports:
      - "5601:5601"
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.1.8:9200
#    volumes:
#      - /Users/jeff/myself/docker/docker/es/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml